config/routes.rb
Rails.application.routes.draw do
  root "users#new"
  get "/users", to: "users#index"

  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true
  validates :email, presence: true
  validates :password, presence: true, length: { in: 3..15 }
end

app/models/user/order.rb
class User::Order < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    # @user = User.new(username: params[:username], email: params[:email], password: params[:password])
    @user = User.new(user_params)

    if @user.save
      redirect_to new_user_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.expect(user: [ :username, :email, :password ])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Re Former" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= form_with model: @user do |form| %>
  <%= form.label :username %>
  <%= form.text_field :username, placeholder: "username" %>
  <%= form.label :email %>
  <%= form.email_field :email, placeholder: "e.g.@example.com" %>
  <%= form.label :password %>
  <%= form.password_field :password, placeholder: "*****" %>
  <%= form.submit "Submit" %>
<% end %>

<%= link_to "Users", users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
    <h2>
      <%= user.username %>
    </h2>
    <li>
      <%= user.email %>
    </li>
    <li>
      <%= user.password %>
    </li>
  <% end %>
</ul>

<%= link_to "Create User", new_user_path %>

app/views/users/new.html.erb
<!-- <form action="/users" accept-charset="UTF-8" method="post">
  <input
type="hidden"
name="authenticity_token"
value="<%= form_authenticity_token %>"
>
  <label for="username">Username:</label>
  <input type="text" id="username" name="user[username]"><br><br>

  <label for="email">Email:</label>
  <input type="text" id="email" name="user[email]"><br><br>

  <label for="password">Password:</label>
  <input type="text" id="password" name="user[password]"><br><br>

  <input type="submit" value="Submit">
</form>

<%= form_with(url: "/users", method:"post") do %>
  <%= label_tag(:username, "Username:") %>
  <%= text_field_tag(:username) %>
  <%= label_tag(:email, "Emal:") %>
  <%= text_field_tag(:email) %>
  <%= label_tag(:password, "Password:") %>
  <%= text_field_tag(:password) %>
  <%= submit_tag("Submit") %>
<% end %>
-->
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
      <% @user.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h1>Create User</h1>

<%= form_with model: @user do |form| %>
  <%= form.label :username %>
  <%= form.text_field :username, placeholder: "username" %>
  <%= form.label :email %>
  <%= form.email_field :email, placeholder: "e.g.@example.com" %>
  <%= form.label :password %>
  <%= form.password_field :password, placeholder: "*****" %>
  <%= form.submit "Submit" %>
<% end %>

<%= link_to "Users", users_path %>